### ISSUE TITLE
ImportError: cannot import name 'startupinfo' from 'skvideo.utils'

### ISSUE THREAD

**Issue by Q8sh2ing** [hyw-dev/AFI-ForwardDeduplicate#2]
i am currently running the code on colab and this error pop-out during inference

/content/GMFSS_Fortuna/AFI-ForwardDeduplicate
Traceback (most recent call last):
  File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/interpolate_video_forward.py", line 66, in <module>
    scene_detection = SvfiTransitionDetection(save, 4,
  File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/Utils_scdet/scdet.py", line 239, in __init__
    from Utils_scdet.utils import Tools
  File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/Utils_scdet/utils.py", line 26, in <module>
    from skvideo.utils import startupinfo
ImportError: cannot import name 'startupinfo' from 'skvideo.utils' (/usr/local/lib/python3.10/dist-packages/skvideo/utils/__init__.py)

.
below are the packages installed 
Requirement already satisfied: scikit-video in /usr/local/lib/python3.10/dist-packages (1.1.11)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from scikit-video) (1.23.5)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from scikit-video) (9.4.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from scikit-video) (1.11.3)

**Comment by 2994dd42d75b0** [comment]
> i am currently running the code on colab and this error pop-out during inference
> 
> /content/GMFSS_Fortuna/AFI-ForwardDeduplicate Traceback (most recent call last): File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/interpolate_video_forward.py", line 66, in scene_detection = SvfiTransitionDetection(save, 4, File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/Utils_scdet/scdet.py", line 239, in **init** from Utils_scdet.utils import Tools File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/Utils_scdet/utils.py", line 26, in from skvideo.utils import startupinfo ImportError: cannot import name 'startupinfo' from 'skvideo.utils' (/usr/local/lib/python3.10/dist-packages/skvideo/utils/**init**.py)
> 
> . below are the packages installed Requirement already satisfied: scikit-video in /usr/local/lib/python3.10/dist-packages (1.1.11) Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from scikit-video) (1.23.5) Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from scikit-video) (9.4.0) Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from scikit-video) (1.11.3)



> i am currently running the code on colab and this error pop-out during inference
> 
> /content/GMFSS_Fortuna/AFI-ForwardDeduplicate Traceback (most recent call last): File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/interpolate_video_forward.py", line 66, in scene_detection = SvfiTransitionDetection(save, 4, File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/Utils_scdet/scdet.py", line 239, in **init** from Utils_scdet.utils import Tools File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/Utils_scdet/utils.py", line 26, in from skvideo.utils import startupinfo ImportError: cannot import name 'startupinfo' from 'skvideo.utils' (/usr/local/lib/python3.10/dist-packages/skvideo/utils/**init**.py)
> 
> . below are the packages installed Requirement already satisfied: scikit-video in /usr/local/lib/python3.10/dist-packages (1.1.11) Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from scikit-video) (1.23.5) Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from scikit-video) (9.4.0) Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from scikit-video) (1.11.3)

its for windows only just remove that line 26 and run

> i am currently running the code on colab and this error pop-out during inference
> 
> /content/GMFSS_Fortuna/AFI-ForwardDeduplicate Traceback (most recent call last): File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/interpolate_video_forward.py", line 66, in scene_detection = SvfiTransitionDetection(save, 4, File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/Utils_scdet/scdet.py", line 239, in **init** from Utils_scdet.utils import Tools File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/Utils_scdet/utils.py", line 26, in from skvideo.utils import startupinfo ImportError: cannot import name 'startupinfo' from 'skvideo.utils' (/usr/local/lib/python3.10/dist-packages/skvideo/utils/**init**.py)
> 
> . below are the packages installed Requirement already satisfied: scikit-video in /usr/local/lib/python3.10/dist-packages (1.1.11) Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from scikit-video) (1.23.5) Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from scikit-video) (9.4.0) Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from scikit-video) (1.11.3)

its for windows only just remove that line 26 and run

**Comment by 2994dd42d75b0** [comment]
> i am currently running the code on colab and this error pop-out during inference
> 
> /content/GMFSS_Fortuna/AFI-ForwardDeduplicate Traceback (most recent call last): File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/interpolate_video_forward.py", line 66, in scene_detection = SvfiTransitionDetection(save, 4, File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/Utils_scdet/scdet.py", line 239, in **init** from Utils_scdet.utils import Tools File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/Utils_scdet/utils.py", line 26, in from skvideo.utils import startupinfo ImportError: cannot import name 'startupinfo' from 'skvideo.utils' (/usr/local/lib/python3.10/dist-packages/skvideo/utils/**init**.py)
> 
> . below are the packages installed Requirement already satisfied: scikit-video in /usr/local/lib/python3.10/dist-packages (1.1.11) Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from scikit-video) (1.23.5) Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from scikit-video) (9.4.0) Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from scikit-video) (1.11.3)

its for windows only just remove that line 26 and run

**Comment by Q8sh2ing** [comment]
> > i am currently running the code on colab and this error pop-out during inference
> > /content/GMFSS_Fortuna/AFI-ForwardDeduplicate Traceback (most recent call last): File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/interpolate_video_forward.py", line 66, in scene_detection = SvfiTransitionDetection(save, 4, File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/Utils_scdet/scdet.py", line 239, in **init** from Utils_scdet.utils import Tools File "/content/GMFSS_Fortuna/AFI-ForwardDeduplicate/Utils_scdet/utils.py", line 26, in from skvideo.utils import startupinfo ImportError: cannot import name 'startupinfo' from 'skvideo.utils' (/usr/local/lib/python3.10/dist-packages/skvideo/utils/**init**.py)
> > . below are the packages installed Requirement already satisfied: scikit-video in /usr/local/lib/python3.10/dist-packages (1.1.11) Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from scikit-video) (1.23.5) Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from scikit-video) (9.4.0) Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from scikit-video) (1.11.3)
> 
> startupinfo is for windows only just remove line 26 (from skvideo.utils import startupinfo) and run

thanks, the code now works perfectly

**Comment by Q8sh2ing** [comment]
i had made a google colab with the code. [here](https://github.com/Q8sh2ing/AFI-ForwardDeduplicate-Colab/blob/main/forward_dedup_Colab.ipynb)

**Comment by hyw-dev** [comment]
Thanks for your colab implementation, I will add it to the project page
