### ISSUE TITLE
How to use other models

### ISSUE THREAD

**Issue by lovmaer** [hyw-dev/AFI-ForwardDeduplicate#3]
Is it possible to use updated rife models like 4.13 with this?

**Comment by hyw-dev** [comment]
Of course, you can replace the RIFE-related files in the models folder, such as IFNet_HDv3, with the latest ones, and simply change the import statement.
Finally, change the latest weight path [here](https://github.com/hyw-dev/AFI-ForwardDeduplicate/blob/main/interpolate_video_forward.py#L85)
