### ISSUE TITLE
Increase Processing Speed Possible?

### ISSUE THREAD

**Issue by 2994dd42d75b0** [hyw-dev/AFI-ForwardDeduplicate#5]
Using GPU to covert and combine frames
ffmpeg -i in.mkv -crf 16 -r 24000/1001-preset slow -c:v hevc_nvenc -profile:v main10 -c:a copy out.mkv

ffmpeg -r 60 -thread_queue_size 5120 -i /O/%09d.png -i out.mkv  -map 0:v -map 1:a -map 1:s -preset slow  -gpu 0 -c:v hevc_nvenc -profile:v main10 -c:a copy output.mkv

Parallelize Frame Reading:
Use multiple threads to read and resize frames concurrently.

Use PyTorch DataLoader:
Utilize torch.utils.data.DataLoader for batch processing and to handle data loading efficiently.

Batch Inference:
Ensure inference is performed on batches of frames instead of one frame at a time.

Can this increase speed,My vram is not fully used
Rife is fast but gmfss is very slow

**Comment by hyw-dev** [comment]
Thank you for paying attention to our work and making suggestions. We have tried all the methods you said, and it cannot be significantly accelerated significantly. A more cost-effective approach is to wait for faster and more advanced vfi algorithms to appear

**Comment by 2994dd42d75b0** [comment]
Thanks for reply I'll wait for gmfss.
