### ISSUE TITLE
how to use latest RIFE in AFI?

### ISSUE THREAD

**Issue by 2994dd42d75b0** [hyw-dev/AFI-ForwardDeduplicate#6]
I copied all files from RIFE 4.18 and also change paths in .py files
Still getting this error

Traceback (most recent call last):
  File "/AFI-ForwardDeduplicate/interpolate_video_forward.py", line 93, in <module>
    model.load_state_dict(convert(torch.load('weights/flownet.pkl')))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for IFNet:
  Unexpected key(s) in state_dict: "teacher.conv0.0.0.weight", "teacher.conv0.0.0.bias", "teacher.conv0.1.0.weight", "teacher.conv0.1.0.bias", "teacher.convblock.0.beta", "teacher.convblock.0.conv.weight", "teacher.convblock.0.conv.bias", "teacher.convblock.1.beta", "teacher.convblock.1.conv.weight", "teacher.convblock.1.conv.bias", "teacher.convblock.2.beta", "teacher.convblock.2.conv.weight", "teacher.convblock.2.conv.bias", "teacher.convblock.3.beta", "teacher.convblock.3.conv.weight", "teacher.convblock.3.conv.bias", "teacher.convblock.4.beta", "teacher.convblock.4.conv.weight", "teacher.convblock.4.conv.bias", "teacher.convblock.5.beta", "teacher.convblock.5.conv.weight", "teacher.convblock.5.conv.bias", "teacher.convblock.6.beta", "teacher.convblock.6.conv.weight", "teacher.convblock.6.conv.bias", "teacher.convblock.7.beta", "teacher.convblock.7.conv.weight", "teacher.convblock.7.conv.bias", "teacher.lastconv.0.weight", "teacher.lastconv.0.bias".

I renamed rife48.pkl to flownet.pkl
Please tell how to fix this

**Comment by hyw-dev** [comment]
try
```python
model.load_state_dicttorch.load('weights/flownet.pkl'))
```

**Comment by 2994dd42d75b0** [comment]
Getting This

interpolate_video_forward.py", line 94, in <module>
    model.load_state_dict(torch.load('weights/flownet.pkl'))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for IFNet:
	Missing key(s) in state_dict: "block0.conv0.0.0.weight", "block0.conv0.0.0.bias", "block0.conv0.1.0.weight", "block0.conv0.1.0.bias", "block0.convblock.0.beta", "block0.convblock.0.conv.weight", "block0.convblock.0.conv.bias", "block0.convblock.1.beta", "block0.convblock.1.conv.weight", "block0.convblock.1.conv.bias", "block0.convblock.2.beta", "block0.convblock.2.conv.weight", "block0.convblock.2.conv.bias", "block0.convblock.3.beta", "block0.convblock.3.conv.weight", "block0.convblock.3.conv.bias", "block0.convblock.4.beta", "block0.convblock.4.conv.weight", "block0.convblock.4.conv.bias", "block0.convblock.5.beta", "block0.convblock.5.conv.weight", "block0.convblock.5.conv.bias", "block0.convblock.6.beta", "block0.convblock.6.conv.weight", "block0.convblock.6.conv.bias", "block0.convblock.7.beta", "block0.convblock.7.conv.weight", "block0.convblock.7.conv.bias", "block0.lastconv.0.weight", "block0.lastconv.0.bias", "block1.conv0.0.0.weight", "block1.conv0.0.0.bias", "block1.conv0.1.0.weight", "block1.conv0.1.0.bias", "block1.convblock.0.beta", "block1.convblock.0.conv.weight", "block1.convblock.0.conv.bias", "block1.convblock.1.beta", "block1.convblock.1.conv.weight", "block1.convblock.1.conv.bias", "block1.convblock.2.beta", "block1.convblock.2.conv.weight", "block1.convblock.2.conv.bias", "block1.convblock.3.beta", "block1.convblock.3.conv.weight", "block1.convblock.3.conv.bias", "block1.convblock.4.beta", "block1.convblock.4.conv.weight", "block1.convblock.4.conv.bias", "block1.convblock.5.beta", "block1.convblock.5.conv.weight", "block1.convblock.5.conv.bias", "block1.convblock.6.beta", "block1.convblock.6.conv.weight", "block1.convblock.6.conv.bias", "block1.convblock.7.beta", "block1.convblock.7.conv.weight", "block1.convblock.7.conv.bias", "block1.lastconv.0.weight", "block1.lastconv.0.bias", "block2.conv0.0.0.weight", "block2.conv0.0.0.bias", "block2.conv0.1.0.weight", "block2.conv0.1.0.bias", "block2.convblock.0.beta", "block2.convblock.0.conv.weight", "block2.convblock.0.conv.bias", "block2.convblock.1.beta", "block2.convblock.1.conv.weight", "block2.convblock.1.conv.bias", "block2.convblock.2.beta", "block2.convblock.2.conv.weight", "block2.convblock.2.conv.bias", "block2.convblock.3.beta", "block2.convblock.3.conv.weight", "block2.convblock.3.conv.bias", "block2.convblock.4.beta", "block2.convblock.4.conv.weight", "block2.convblock.4.conv.bias", "block2.convblock.5.beta", "block2.convblock.5.conv.weight", "block2.convblock.5.conv.bias", "block2.convblock.6.beta", "block2.convblock.6.conv.weight", "block2.convblock.6.conv.bias", "block2.convblock.7.beta", "block2.convblock.7.conv.weight", "block2.convblock.7.conv.bias", "block2.lastconv.0.weight", "block2.lastconv.0.bias", "block3.conv0.0.0.weight", "block3.conv0.0.0.bias", "block3.conv0.1.0.weight", "block3.conv0.1.0.bias", "block3.convblock.0.beta", "block3.convblock.0.conv.weight", "block3.convblock.0.conv.bias", "block3.convblock.1.beta", "block3.convblock.1.conv.weight", "block3.convblock.1.conv.bias", "block3.convblock.2.beta", "block3.convblock.2.conv.weight", "block3.convblock.2.conv.bias", "block3.convblock.3.beta", "block3.convblock.3.conv.weight", "block3.convblock.3.conv.bias", "block3.convblock.4.beta", "block3.convblock.4.conv.weight", "block3.convblock.4.conv.bias", "block3.convblock.5.beta", "block3.convblock.5.conv.weight", "block3.convblock.5.conv.bias", "block3.convblock.6.beta", "block3.convblock.6.conv.weight", "block3.convblock.6.conv.bias", "block3.convblock.7.beta", "block3.convblock.7.conv.weight", "block3.convblock.7.conv.bias", "block3.lastconv.0.weight", "block3.lastconv.0.bias", "encode.cnn0.weight", "encode.cnn0.bias", "encode.cnn1.weight", "encode.cnn1.bias", "encode.cnn2.weight", "encode.cnn2.bias", "encode.cnn3.weight", "encode.cnn3.bias". 
	Unexpected key(s) in state_dict: "module.block0.conv0.0.0.weight", "module.block0.conv0.0.0.bias", "module.block0.conv0.1.0.weight", "module.block0.conv0.1.0.bias", "module.block0.convblock.0.beta", "module.block0.convblock.0.conv.weight", "module.block0.convblock.0.conv.bias", "module.block0.convblock.1.beta", "module.block0.convblock.1.conv.weight", "module.block0.convblock.1.conv.bias", "module.block0.convblock.2.beta", "module.block0.convblock.2.conv.weight", "module.block0.convblock.2.conv.bias", "module.block0.convblock.3.beta", "module.block0.convblock.3.conv.weight", "module.block0.convblock.3.conv.bias", "module.block0.convblock.4.beta", "module.block0.convblock.4.conv.weight", "module.block0.convblock.4.conv.bias", "module.block0.convblock.5.beta", "module.block0.convblock.5.conv.weight", "module.block0.convblock.5.conv.bias", "module.block0.convblock.6.beta", "module.block0.convblock.6.conv.weight", "module.block0.convblock.6.conv.bias", "module.block0.convblock.7.beta", "module.block0.convblock.7.conv.weight", "module.block0.convblock.7.conv.bias", "module.block0.lastconv.0.weight", "module.block0.lastconv.0.bias", "module.block1.conv0.0.0.weight", "module.block1.conv0.0.0.bias", "module.block1.conv0.1.0.weight", "module.block1.conv0.1.0.bias", "module.block1.convblock.0.beta", "module.block1.convblock.0.conv.weight", "module.block1.convblock.0.conv.bias", "module.block1.convblock.1.beta", "module.block1.convblock.1.conv.weight", "module.block1.convblock.1.conv.bias", "module.block1.convblock.2.beta", "module.block1.convblock.2.conv.weight", "module.block1.convblock.2.conv.bias", "module.block1.convblock.3.beta", "module.block1.convblock.3.conv.weight", "module.block1.convblock.3.conv.bias", "module.block1.convblock.4.beta", "module.block1.convblock.4.conv.weight", "module.block1.convblock.4.conv.bias", "module.block1.convblock.5.beta", "module.block1.convblock.5.conv.weight", "module.block1.convblock.5.conv.bias", "module.block1.convblock.6.beta", "module.block1.convblock.6.conv.weight", "module.block1.convblock.6.conv.bias", "module.block1.convblock.7.beta", "module.block1.convblock.7.conv.weight", "module.block1.convblock.7.conv.bias", "module.block1.lastconv.0.weight", "module.block1.lastconv.0.bias", "module.block2.conv0.0.0.weight", "module.block2.conv0.0.0.bias", "module.block2.conv0.1.0.weight", "module.block2.conv0.1.0.bias", "module.block2.convblock.0.beta", "module.block2.convblock.0.conv.weight", "module.block2.convblock.0.conv.bias", "module.block2.convblock.1.beta", "module.block2.convblock.1.conv.weight", "module.block2.convblock.1.conv.bias", "module.block2.convblock.2.beta", "module.block2.convblock.2.conv.weight", "module.block2.convblock.2.conv.bias", "module.block2.convblock.3.beta", "module.block2.convblock.3.conv.weight", "module.block2.convblock.3.conv.bias", "module.block2.convblock.4.beta", "module.block2.convblock.4.conv.weight", "module.block2.convblock.4.conv.bias", "module.block2.convblock.5.beta", "module.block2.convblock.5.conv.weight", "module.block2.convblock.5.conv.bias", "module.block2.convblock.6.beta", "module.block2.convblock.6.conv.weight", "module.block2.convblock.6.conv.bias", "module.block2.convblock.7.beta", "module.block2.convblock.7.conv.weight", "module.block2.convblock.7.conv.bias", "module.block2.lastconv.0.weight", "module.block2.lastconv.0.bias", "module.block3.conv0.0.0.weight", "module.block3.conv0.0.0.bias", "module.block3.conv0.1.0.weight", "module.block3.conv0.1.0.bias", "module.block3.convblock.0.beta", "module.block3.convblock.0.conv.weight", "module.block3.convblock.0.conv.bias", "module.block3.convblock.1.beta", "module.block3.convblock.1.conv.weight", "module.block3.convblock.1.conv.bias", "module.block3.convblock.2.beta", "module.block3.convblock.2.conv.weight", "module.block3.convblock.2.conv.bias", "module.block3.convblock.3.beta", "module.block3.convblock.3.conv.weight", "module.block3.convblock.3.conv.bias", "module.block3.convblock.4.beta", "module.block3.convblock.4.conv.weight", "module.block3.convblock.4.conv.bias", "module.block3.convblock.5.beta", "module.block3.convblock.5.conv.weight", "module.block3.convblock.5.conv.bias", "module.block3.convblock.6.beta", "module.block3.convblock.6.conv.weight", "module.block3.convblock.6.conv.bias", "module.block3.convblock.7.beta", "module.block3.convblock.7.conv.weight", "module.block3.convblock.7.conv.bias", "module.block3.lastconv.0.weight", "module.block3.lastconv.0.bias", "module.encode.cnn0.weight", "module.encode.cnn0.bias", "module.encode.cnn1.weight", "module.encode.cnn1.bias", "module.encode.cnn2.weight", "module.encode.cnn2.bias", "module.encode.cnn3.weight", "module.encode.cnn3.bias", "module.teacher.conv0.0.0.weight", "module.teacher.conv0.0.0.bias", "module.teacher.conv0.1.0.weight", "module.teacher.conv0.1.0.bias", "module.teacher.convblock.0.beta", "module.teacher.convblock.0.conv.weight", "module.teacher.convblock.0.conv.bias", "module.teacher.convblock.1.beta", "module.teacher.convblock.1.conv.weight", "module.teacher.convblock.1.conv.bias", "module.teacher.convblock.2.beta", "module.teacher.convblock.2.conv.weight", "module.teacher.convblock.2.conv.bias", "module.teacher.convblock.3.beta", "module.teacher.convblock.3.conv.weight", "module.teacher.convblock.3.conv.bias", "module.teacher.convblock.4.beta", "module.teacher.convblock.4.conv.weight", "module.teacher.convblock.4.conv.bias", "module.teacher.convblock.5.beta", "module.teacher.convblock.5.conv.weight", "module.teacher.convblock.5.conv.bias", "module.teacher.convblock.6.beta", "module.teacher.convblock.6.conv.weight", "module.teacher.convblock.6.conv.bias", "module.teacher.convblock.7.beta", "module.teacher.convblock.7.conv.weight", "module.teacher.convblock.7.conv.bias", "module.teacher.lastconv.0.weight", "module.teacher.lastconv.0.bias".

**Comment by hyw-dev** [comment]
model.load_state_dict(convert(torch.load('weights/flownet.pkl')),strict=false)

**Comment by 2994dd42d75b0** [comment]
Loaded model
  0% 0/245.0 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/AFI-ForwardDeduplicate/interpolate_video_forward.py", line 270, in <module>
    output0, count = decrease_inference(queue_input.copy())
  File "/AFI-ForwardDeduplicate/interpolate_video_forward.py", line 191, in decrease_inference
    to_numpy(make_inf(inp0, inp1, scale, 0.5))
  File "/AFI-ForwardDeduplicate/interpolate_video_forward.py", line 118, in to_numpy
    return tensor.squeeze(0).permute(1, 2, 0).cpu().numpy() * 255.
AttributeError: 'tuple' object has no attribute 'squeeze'
FATAL: exception not rethrown

Same error Using RIFE 4.18 to 4.22

**Comment by 2994dd42d75b0** [comment]
Loaded model
0% 0/245.0 [00:00<?, ?it/s]Traceback (most recent call last):
File "/AFI-ForwardDeduplicate/interpolate_video_forward.py", line 111, in <module>
    model.load_state_dict(convert(torch.load('weights/flownet.pkl')), strict=False)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for IFNet:
	size mismatch for block0.conv0.0.0.weight: copying a param with shape torch.Size([128, 23, 3, 3]) from checkpoint, the shape in current model is torch.Size([96, 7, 3, 3]).
	size mismatch for block0.conv0.0.0.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([96]).
	size mismatch for block0.conv0.1.0.weight: copying a param with shape torch.Size([256, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 96, 3, 3]).
	size mismatch for block0.conv0.1.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for block0.convblock.0.beta: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 192, 1, 1]).
	size mismatch for block0.convblock.0.conv.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 192, 3, 3]).
	size mismatch for block0.convblock.0.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for block0.convblock.1.beta: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 192, 1, 1]).
	size mismatch for block0.convblock.1.conv.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 192, 3, 3]).
	size mismatch for block0.convblock.1.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for block0.convblock.2.beta: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 192, 1, 1]).
	size mismatch for block0.convblock.2.conv.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 192, 3, 3]).
	size mismatch for block0.convblock.2.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for block0.convblock.3.beta: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 192, 1, 1]).
	size mismatch for block0.convblock.3.conv.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 192, 3, 3]).
	size mismatch for block0.convblock.3.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for block0.convblock.4.beta: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 192, 1, 1]).
	size mismatch for block0.convblock.4.conv.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 192, 3, 3]).
	size mismatch for block0.convblock.4.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for block0.convblock.5.beta: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 192, 1, 1]).
	size mismatch for block0.convblock.5.conv.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 192, 3, 3]).
	size mismatch for block0.convblock.5.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for block0.convblock.6.beta: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 192, 1, 1]).
	size mismatch for block0.convblock.6.conv.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 192, 3, 3]).
	size mismatch for block0.convblock.6.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for block0.convblock.7.beta: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 192, 1, 1]).
	size mismatch for block0.convblock.7.conv.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([192, 192, 3, 3]).
	size mismatch for block0.convblock.7.conv.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([192]).
	size mismatch for block0.lastconv.0.weight: copying a param with shape torch.Size([256, 52, 4, 4]) from checkpoint, the shape in current model is torch.Size([192, 24, 4, 4]).
	size mismatch for block0.lastconv.0.bias: copying a param with shape torch.Size([52]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for block1.conv0.0.0.weight: copying a param with shape torch.Size([96, 36, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 12, 3, 3]).
	size mismatch for block1.conv0.0.0.bias: copying a param with shape torch.Size([96]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for block1.conv0.1.0.weight: copying a param with shape torch.Size([192, 96, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 64, 3, 3]).
	size mismatch for block1.conv0.1.0.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for block1.convblock.0.beta: copying a param with shape torch.Size([1, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
	size mismatch for block1.convblock.0.conv.weight: copying a param with shape torch.Size([192, 192, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for block1.convblock.0.conv.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for block1.convblock.1.beta: copying a param with shape torch.Size([1, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
	size mismatch for block1.convblock.1.conv.weight: copying a param with shape torch.Size([192, 192, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for block1.convblock.1.conv.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for block1.convblock.2.beta: copying a param with shape torch.Size([1, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
	size mismatch for block1.convblock.2.conv.weight: copying a param with shape torch.Size([192, 192, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for block1.convblock.2.conv.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for block1.convblock.3.beta: copying a param with shape torch.Size([1, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
	size mismatch for block1.convblock.3.conv.weight: copying a param with shape torch.Size([192, 192, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for block1.convblock.3.conv.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for block1.convblock.4.beta: copying a param with shape torch.Size([1, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
	size mismatch for block1.convblock.4.conv.weight: copying a param with shape torch.Size([192, 192, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for block1.convblock.4.conv.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for block1.convblock.5.beta: copying a param with shape torch.Size([1, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
	size mismatch for block1.convblock.5.conv.weight: copying a param with shape torch.Size([192, 192, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for block1.convblock.5.conv.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for block1.convblock.6.beta: copying a param with shape torch.Size([1, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
	size mismatch for block1.convblock.6.conv.weight: copying a param with shape torch.Size([192, 192, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for block1.convblock.6.conv.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for block1.convblock.7.beta: copying a param with shape torch.Size([1, 192, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).
	size mismatch for block1.convblock.7.conv.weight: copying a param with shape torch.Size([192, 192, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3]).
	size mismatch for block1.convblock.7.conv.bias: copying a param with shape torch.Size([192]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for block1.lastconv.0.weight: copying a param with shape torch.Size([192, 52, 4, 4]) from checkpoint, the shape in current model is torch.Size([128, 24, 4, 4]).
	size mismatch for block1.lastconv.0.bias: copying a param with shape torch.Size([52]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for block2.conv0.0.0.weight: copying a param with shape torch.Size([48, 36, 3, 3]) from checkpoint, the shape in current model is torch.Size([48, 12, 3, 3]).
	size mismatch for block2.lastconv.0.weight: copying a param with shape torch.Size([96, 52, 4, 4]) from checkpoint, the shape in current model is torch.Size([96, 24, 4, 4]).
	size mismatch for block2.lastconv.0.bias: copying a param with shape torch.Size([52]) from checkpoint, the shape in current model is torch.Size([24]).
	size mismatch for block3.conv0.0.0.weight: copying a param with shape torch.Size([24, 36, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 12, 3, 3]).
	size mismatch for block3.conv0.0.0.bias: copying a param with shape torch.Size([24]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for block3.conv0.1.0.weight: copying a param with shape torch.Size([48, 24, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 32, 3, 3]).
	size mismatch for block3.conv0.1.0.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for block3.convblock.0.beta: copying a param with shape torch.Size([1, 48, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 64, 1, 1]).
	size mismatch for block3.convblock.0.conv.weight: copying a param with shape torch.Size([48, 48, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for block3.convblock.0.conv.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for block3.convblock.1.beta: copying a param with shape torch.Size([1, 48, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 64, 1, 1]).
	size mismatch for block3.convblock.1.conv.weight: copying a param with shape torch.Size([48, 48, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for block3.convblock.1.conv.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for block3.convblock.2.beta: copying a param with shape torch.Size([1, 48, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 64, 1, 1]).
	size mismatch for block3.convblock.2.conv.weight: copying a param with shape torch.Size([48, 48, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for block3.convblock.2.conv.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for block3.convblock.3.beta: copying a param with shape torch.Size([1, 48, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 64, 1, 1]).
	size mismatch for block3.convblock.3.conv.weight: copying a param with shape torch.Size([48, 48, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for block3.convblock.3.conv.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for block3.convblock.4.beta: copying a param with shape torch.Size([1, 48, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 64, 1, 1]).
	size mismatch for block3.convblock.4.conv.weight: copying a param with shape torch.Size([48, 48, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for block3.convblock.4.conv.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for block3.convblock.5.beta: copying a param with shape torch.Size([1, 48, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 64, 1, 1]).
	size mismatch for block3.convblock.5.conv.weight: copying a param with shape torch.Size([48, 48, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for block3.convblock.5.conv.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for block3.convblock.6.beta: copying a param with shape torch.Size([1, 48, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 64, 1, 1]).
	size mismatch for block3.convblock.6.conv.weight: copying a param with shape torch.Size([48, 48, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for block3.convblock.6.conv.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for block3.convblock.7.beta: copying a param with shape torch.Size([1, 48, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 64, 1, 1]).
	size mismatch for block3.convblock.7.conv.weight: copying a param with shape torch.Size([48, 48, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for block3.convblock.7.conv.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for block3.lastconv.0.weight: copying a param with shape torch.Size([48, 52, 4, 4]) from checkpoint, the shape in current model is torch.Size([64, 24, 4, 4]).
	size mismatch for block3.lastconv.0.bias: copying a param with shape torch.Size([52]) from checkpoint, the shape in current model is torch.Size([24]).

**Comment by 2994dd42d75b0** [comment]
Loaded model
  0% 0/143.0 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/interpolate_video_forward_anyfps.py", line 278, in <module>
    output0, count = decrease_inference(queue_input.copy())
  File "/interpolate_video_forward_anyfps.py", line 207, in decrease_inference
    to_numpy(make_inf(inp0, inp1, scale, 0.5))
  File "/interpolate_video_forward_anyfps.py", line 133, in to_numpy
    return tensor.squeeze(0).permute(1, 2, 0).cpu().numpy() * 255.
AttributeError: 'tuple' object has no attribute 'squeeze'
terminate called without an active exception

**Comment by hyw-dev** [comment]
In the case of RIFE 4.22, you need to return merged instead of merged[3].

**Comment by 2994dd42d75b0** [comment]
Working Now Perfectly

Thanks
